version: '3.9'
services:
  app:
    container_name: app
    build: 
      context: .
    command: bash -E -c 'npm start'
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - .env
  db:
    container_name: db
    image: 'postgres:14'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
